workflows:
  deploy_macos:
    name: "[macOS] Deploy to App Store"
    instance_type: mac_mini_m2
    max_build_duration: 120
    integrations:
      app_store_connect: App Elevate Distribution
    environment:
      flutter: 3.24.5
      xcode: 16.0 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: 1.16.2
      groups:
        # Exports the SHOREBIRD_TOKEN environment variable
        - shorebird
        - sentry
        - fastlane
    scripts:
      - name: use appstore keys
        script: |
          git fetch --unshallow
          git revert 1f6ed5030970b24c761a61bf7412e98919f3a494
      - name: Setup flutterfire
        script: |
          dart pub global activate flutterfire_cli

      - name: Get Certs
        script: |
          cd macos
          bundle install
          bundle exec fastlane setup_ci_keychain
          cd ..

      - name: 🚀 Build Flutter
        script: |
          security unlock-keychain -p temp ~/Library/Keychains/AppSigning-db && flutter build macos
          security unlock-keychain -p temp ~/Library/Keychains/AppSigning-db && flutter build macos

      - name: 🚀 Sign and upload symbols to Sentry
        script: |
          cd macos
          bundle exec fastlane release_ci
          cd ..

    artifacts:
      - /Users/builder/export_options.plist
      - macos/*.pkg
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - protitom@gmail.com
        notify:
          failure: true # To receive a notification when a build fails
          success: false
      app_store_connect:
        auth: integration

  deploy_ios:
    name: "[iOS] Deploy to App Store"
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: App Elevate Distribution
    environment:
      ios_signing:
        distribution_type: app_store # or app_store | development | enterprise
        bundle_identifier: cz.appelevate.autojidelna # for wildcard provisional profiles
      flutter: 3.24.5
      xcode: 16.0 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: 1.16.2
      vars:
        PATCH: "false"
        FLUTTER_VERSION: "3.24.2"
      groups:
        # Exports the SHOREBIRD_TOKEN environment variable
        - shorebird
        - sentry
    scripts:
      - name: Certs
        script: |
          xcode-project use-profiles

      - name: Setup flutterfire
        script: |
          dart pub global activate flutterfire_cli

      - name: Fixing Plist
        script: |
          # Locate your plist file path here, change the file path to match your project
          EXTENSION_PLIST_PATH="/Users/builder/export_options.plist"

          APP_VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          BUILD_NUMBER=$(grep '^version:' pubspec.yaml | cut -d '+' -f 2)

          # Function to check if a key exists in the plist
          check_and_update_plist() {
            local key=$1
            local value=$2
            local value_type=$3  # Add data type as a parameter (string, integer, or boolean)
            local plist_path=$4

            # Check if the key exists in the plist
            if /usr/libexec/PlistBuddy -c "Print :$key" "$plist_path" 2>/dev/null; then
              /usr/libexec/PlistBuddy -c "Set :$key $value" "$plist_path"
            else
              /usr/libexec/PlistBuddy -c "Add :$key $value_type $value" "$plist_path"
            fi
          }

          # Update CFBundleShortVersionString
          check_and_update_plist "CFBundleShortVersionString" "$APP_VERSION" "string" "$EXTENSION_PLIST_PATH"

          # Update CFBundleVersion
          check_and_update_plist "CFBundleVersion" "$BUILD_NUMBER" "string" "$EXTENSION_PLIST_PATH"

          # Update manageAppVersionAndBuildNumber
          check_and_update_plist "manageAppVersionAndBuildNumber" "false" "bool" "$EXTENSION_PLIST_PATH"

      - name: 🐦 Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV

      - name: 🚀 Shorebird Release
        script: |
          if [ "$PATCH" = "true" ]; then
            shorebird patch ios --release-version=$(sed -n 's/^version: \(.*\)$/\1/p' pubspec.yaml) --export-options-plist=/Users/builder/export_options.plist
          else
            shorebird release ios --export-options-plist=/Users/builder/export_options.plist --flutter-version=$FLUTTER_VERSION
          fi

      - name: Upload symbols to Sentry
        script: |
          cd ios
          bundle exec fastlane release_ci
          cd ..

      - name: Cancel if it's a patch release
        script: |
          if [ "$PATCH" = "true" ]; then
            rm -rf build/ios/ipa
          fi

    artifacts:
      - /Users/builder/export_options.plist
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - /Users/builder/Library/Application Support/shorebird/logs/*.log
    publishing:
      email:
        recipients:
          - protitom@gmail.com
        notify:
          failure: true # To receive a notification when a build fails
          success: false
      app_store_connect:
        auth: integration
