# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do

    # Fetch App Store Certificates
    build_app(
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      export_options: {
        signingStyle: "automatic",
        }
      )
    begin
    api_key = app_store_connect_api_key(
          key_id: "VPJ6V9H7X3",
          issuer_id: "d7e6d3c1-f68b-4764-9d30-0d74a9888f6c",
          key_filepath: "./../private_keys/app_store.p8",
          in_house: false
      )
    upload_to_testflight(skip_waiting_for_build_processing: true)
    rescue => e
      sh "open -a transporter"
      sh "open -R ./../APPE\\ Coree.pkg"
    end
  end
end
