# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create Keychain for Ci/CD"
  lane :setup_ci_keychain do 
    # Create the keychain
    create_keychain(
        name: "AppSigning",
        default_keychain: true,
        add_to_search_list: true,
        unlock: true,
        password: "temp"
        )

    match(
      readonly: true,
      keychain_name: "AppSigning",
      keychain_password: "temp",
      type: "appstore"
    )
  end

  desc "Push a new release build to the App Store"
  lane :release_ci do
    create_keychain(
      name: "AppSigning",
      default_keychain: true,
      add_to_search_list: true,
      unlock: true,
      password: "temp"
      )

    match(
      readonly: true,
      keychain_name: "AppSigning",
      keychain_password: "temp",
      type: "appstore"
      )
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      )
    sentry_debug_files_upload(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'app-elevate',
      project_slug: 'appe-coree',
      include_sources: true, # Optional. For source context.
    )
    delete_keychain(
      name: "AppSigning"
    )
    sh "security default-keychain -s login.keychain || true"
  end

  desc "Push a new release build to the App Store"
  lane :release do
    match(
      readonly: true,
      type: "appstore"
      )
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      )
    sentry_debug_files_upload(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'app-elevate',
      project_slug: 'appe-coree',
      include_sources: true, # Optional. For source context.
    )
    begin
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_filepath: "./../private_keys/app_store.p8",
      in_house: false
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)[0]
    )
    rescue => e
      sh "open -a transporter"
      sh "open -R ../Runner.ipa"
    end
  end
end
