# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    # Load the API Key
    match(
      keychain_name: "login.keychain",
      keychain_password: ENV["IOS_KEYCHAIN_PASSWORD"],
    )
    api_key = app_store_connect_api_key(
          key_id: "VPJ6V9H7X3",
          issuer_id: "d7e6d3c1-f68b-4764-9d30-0d74a9888f6c",
          key_filepath: "./private_keys/AuthKey_VPJ6V9H7X3.p8",
          in_house: false
      )
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
      export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      destination: 'generic/platform=iOS'
      )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
