# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload Source Maps to Sentry"
  lane :release_ci do
    sentry_debug_files_upload(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'app-elevate',
      project_slug: 'autojidelna',
      include_sources: true, # Optional. For source context.
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    sh 'mv ../../build/ios/ipa/autojidelna.ipa ../Runner.ipa'
    sentry_debug_files_upload(
      auth_token: ENV["SENTRY_AUTH_TOKEN"],
      org_slug: 'app-elevate',
      project_slug: 'autojidelna',
      include_sources: true, # Optional. For source context.
    )
    begin
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_filepath: "./../private_keys/app_store.p8",
      in_house: false
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)[0]
    )
    rescue => e
      sh "open -a transporter"
      sh "open -R ../Runner.ipa"
    end
  end
end
