// This file is "main.dart"
import 'package:autojidelna/src/types/freezed/account/account.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'logged_accounts.freezed.dart';
// optional: Since our LoggedAccounts class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'logged_accounts.g.dart';

@unfreezed
class LoggedAccounts with _$LoggedAccounts {
  factory LoggedAccounts({
    @JsonKey(name: 'logged_in_username') String? loggedInUsername,
    @JsonKey(name: 'accounts') @Default([]) List<Account> accounts,
  }) = _LoggedAccounts;

  factory LoggedAccounts.fromJson(Map<String, Object?> json) => _$LoggedAccountsFromJson(json);
}
