// This file is "main.dart"
import 'package:autojidelna/src/types/freezed/account/account.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'logged_accounts.freezed.dart';
// optional: Since our LoggedAccounts class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'logged_accounts.g.dart';

@unfreezed
class LoggedAccounts with _$LoggedAccounts {
  const factory LoggedAccounts({
    @JsonKey(name: 'currently_logged_in_id') int? currentlyLoggedInId,
    @JsonKey(name: 'users') @Default([]) List<Account> users,
  }) = _LoggedAccounts;

  factory LoggedAccounts.fromJson(Map<String, Object?> json) => _$LoggedAccountsFromJson(json);
}
